http {
    server {
        listen 8080;
        listen 8081; # Error: duplicate directive
        
        server_name test_server;
        root ./www;
        root ./html; # Error: duplicate directive
        
        client_max_body_size 100;
        
        # Error: invalid code
        error_page 99 /error.html;
        
        # Error: duplicate location
        location /test {
            allow_methods GET;
        }
        location /test {
            allow_methods POST;
        }
    }
}