http {
	server {
		listen 8080;
		server_name duplicate_test;
		root ./www;

		location /capybara {
			allow_methods GET;
		}

		# This block call an error "duplicate location path found"
		location /capybara {
			allow_methods POST;
		}
	}
}