http {
	client_max_body_size 2M;

	server {
		listen 4245;
		server_name localhost;
		# Путь должен быть абсолютным или четко от корня проекта
		root ./var/www/html;
		index index.html;

		# Эта локация нужна тестам!
		location /upload {
			# Скрипт шлет 9000 байт (успех для 10K) и 11000 байт (413 для 10K)
			client_max_body_size 10K;
			allow_methods POST GET;
		}

		# Для теста на 1.1МБ (1100000 байт) на корень /
		location / {
			client_max_body_size 1M;
			allow_methods GET POST;
		}
	}
}
