http {
	server {
		listen 8080;
		server_name first.com;
		root ./var/www/html;
		index index.html;
		allow_methods GET;

		location / {
			root ./var/www/html;
			index index.html;
		}
	}
	server {
		listen 8080;
		server_name second.com;
		root ./var/www/html/about;
		index about.html;
		allow_methods GET;

		location / {
			root ./var/www/html/about;
			index about.html;
		}
	}
}