http {

    index index.html;


    server {
        listen       4241;
        server_name  google.com;

        error_page 404 /errors/404.html;

        location / {
            client_max_body_size 0;
            index text/html;    
        }
        location /temp/ {
            return 302 /; # Giving a redirection to another location
        }
        location /upload/{
            upload_store /tmp/uploads 1;
        }
        location /about {
            index about.html;
        }
    }
    server {
        listen       4242;
        server_name  bigserver;

        location / {
            client_max_body_size 0;
        }
    }
}